version: "2.2"
services:
    homeassistant:
        restart: always
        container_name: homeassistant
        image: homeassistant/home-assistant:0.93.1
        volumes:
            - "/etc/homekit/home-assistant/conf:/config"
            - "/etc/localtime:/etc/localtime:ro"
            - "/tmp/homekit:/tmp/homekit"
        network_mode: host

    mosquitto:
        restart: always
        container_name: mosquitto
        image: eclipse-mosquitto:1.5.8
        volumes:
            - "/etc/homekit/production/mosquitto:/mosquitto/config"
            - "/var/lib/mosquitto:/mosquitto/data"
        ports:
            - "0.0.0.0:1883:1883"
            - "0.0.0.0:9001:9001"

    influxdb:
        restart: always
        container_name: influxdb
        image: influxdb:1.7.5
        volumes:
            - "/var/lib/influxdb:/var/lib/influxdb"
        ports:
            - 8086:8086

    grafana:
        restart: always
        container_name: grafana
        image: grafana/grafana:6.1.3
        volumes:
            - "/var/lib/grafana:/var/lib/grafana"
        links:
            - influxdb
        ports:
            - '0.0.0.0:3000:3000'
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: 'true'

    nodered:
        restart: always
        container_name: nodered
        image: nodered/node-red-docker:0.20.5-v8
        volumes:
            - "/etc/homekit/node-red:/data"
            - "/etc/localtime:/etc/localtime:ro"
            - "/tmp/homekit:/tmp/homekit"
        network_mode: host
        ports:
            - '0.0.0.0:1880:1880'
