esphome:
  name: garage
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "garage"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    pin: D6
    id: relay
  - platform: template
    id: relay_toggle
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
      inverted: true
    id: bottom_end_stop
    filters:
      - delayed_on: 10ms

cover:
  - platform: template
    device_class: garage
    name: "Garage Door"
    lambda: |-
      if (id(bottom_end_stop).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
    open_action:
      - switch.turn_on: relay_toggle
    close_action:
      - switch.turn_on: relay_toggle
    stop_action:
      - switch.turn_on: relay_toggle
    optimistic: true
