esphome:
  name: upstairs_cabinet
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: GPIO14
    model: AM2302
    humidity:
      name: "Upstairs Humidity"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    temperature:
      name: "Upstairs Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    update_interval: 30s
