- alias: Turn on tree lights at sunset
  id: '1521860501554'
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.sprinkle_tree_lights
    service: switch.turn_on
- alias: Turn off tree lights at 10:30pm
  id: '1521860693473'
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sprinkle_tree_lights
    service: switch.turn_off
- alias: Open Nicks Blinds at 8am weekdays
  id: '1521974624434'
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.blindkit_nick_front
  - service: cover.open_cover
    data:
      entity_id: cover.blindkit_nick_side
- id: '1521975760989'
  alias: Water backyard at 9am
  trigger:
  - at: 09:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sprinkle_back_yard
    service: switch.turn_on
- alias: Water herbs at 2:00pm
  trigger:
  - at: '14:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sprinkle_herbs
    service: switch.turn_on
  id: eb5b8733e87443b99407c3ff5054200b
- alias: Water lavender at 2:10pm
  trigger:
  - at: '14:10:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sprinkle_lavender
    service: switch.turn_on
  id: 27e25a964ccd4cd8a82d57bc0e2faa48
- id: '1527999374641'
  alias: Family & Kitch up 6.15am
  trigger:
  - at: 06:15:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_front_3_door_right
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_front_2_door_left
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_front_1_left
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_back_right
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_back_left
    service: cover.open_cover
- id: '1528004893114'
  alias: Family & Kitch Part Down 5:30pm
  trigger:
  - at: '17:30:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      entity_id: cover.blindkit_front_4_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_2_door_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_1_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_back_left
    service: cover.close_cover
- id: '1528005097586'
  alias: Family & Kitch Down all 10pm
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_front_4_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_3_door_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_2_door_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_1_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_back_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_back_left
    service: cover.close_cover
- id: '1528005630746'
  alias: Up-Hall Blockout Open 6.45am
  trigger:
  - at: 06:45:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_upstairs_hall_blockout
    service: cover.open_cover
- id: '1528005697426'
  alias: Up-Hall Blockout Down 5.30pm
  trigger:
  - at: '17:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_upstairs_hall_blockout
    service: cover.close_cover
